# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIdesign.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import qtresources_rc

class Ui_VisualSP(object):
    def setupUi(self, VisualSP):
        VisualSP.setObjectName("VisualSP")
        VisualSP.setEnabled(True)
        VisualSP.resize(1988, 897)
        VisualSP.setAutoFillBackground(False)
        VisualSP.setStyleSheet("")
        VisualSP.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.Main = QtWidgets.QWidget(VisualSP)
        self.Main.setObjectName("Main")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.Main)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 1993, 900))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(300, 0))
        self.stackedWidget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.stackedWidget.setObjectName("stackedWidget")
        self.LoggedOut = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LoggedOut.sizePolicy().hasHeightForWidth())
        self.LoggedOut.setSizePolicy(sizePolicy)
        self.LoggedOut.setMinimumSize(QtCore.QSize(300, 0))
        self.LoggedOut.setMaximumSize(QtCore.QSize(300, 16777215))
        self.LoggedOut.setStyleSheet("background-color: rgb(51, 58, 74);")
        self.LoggedOut.setObjectName("LoggedOut")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.LoggedOut)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(-1, -1, 299, 908))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.loginLabel = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginLabel.sizePolicy().hasHeightForWidth())
        self.loginLabel.setSizePolicy(sizePolicy)
        self.loginLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.loginLabel.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(48)
        self.loginLabel.setFont(font)
        self.loginLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.loginLabel.setObjectName("loginLabel")
        self.verticalLayout.addWidget(self.loginLabel)
        self.login = QtWidgets.QWidget(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login.sizePolicy().hasHeightForWidth())
        self.login.setSizePolicy(sizePolicy)
        self.login.setMinimumSize(QtCore.QSize(0, 60))
        self.login.setMaximumSize(QtCore.QSize(16777215, 60))
        self.login.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.login.setObjectName("login")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.login)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 2, 265, 63))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.userName = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(26)
        self.userName.setFont(font)
        self.userName.setStyleSheet("background-color: rgb(111, 127, 161);")
        self.userName.setFrame(False)
        self.userName.setObjectName("userName")
        self.horizontalLayout_4.addWidget(self.userName)
        self.loginButton = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.loginButton.setStyleSheet(":hover {\n"
"    background-color: rgb(91, 103, 131);\n"
"}\n"
"\n"
"QToolButton {\n"
"\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/assets/arrowRight.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loginButton.setIcon(icon)
        self.loginButton.setIconSize(QtCore.QSize(25, 35))
        self.loginButton.setObjectName("loginButton")
        self.horizontalLayout_4.addWidget(self.loginButton)
        self.verticalLayout.addWidget(self.login)
        self.NewUser = QtWidgets.QWidget(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NewUser.sizePolicy().hasHeightForWidth())
        self.NewUser.setSizePolicy(sizePolicy)
        self.NewUser.setMinimumSize(QtCore.QSize(0, 50))
        self.NewUser.setMaximumSize(QtCore.QSize(16777215, 50))
        self.NewUser.setObjectName("NewUser")
        self.toolButton = QtWidgets.QToolButton(self.NewUser)
        self.toolButton.setGeometry(QtCore.QRect(21, -1, 263, 49))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton.sizePolicy().hasHeightForWidth())
        self.toolButton.setSizePolicy(sizePolicy)
        self.toolButton.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(26)
        self.toolButton.setFont(font)
        self.toolButton.setStyleSheet("QToolButton {\n"
"    background-color: rgb(75, 85, 109);\n"
"}\n"
"\n"
":hover {\n"
"    background-color: rgb(91, 103, 131);\n"
"}\n"
"")
        self.toolButton.setObjectName("toolButton")
        self.verticalLayout.addWidget(self.NewUser)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.stackedWidget.addWidget(self.LoggedOut)
        self.LoggedIn = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LoggedIn.sizePolicy().hasHeightForWidth())
        self.LoggedIn.setSizePolicy(sizePolicy)
        self.LoggedIn.setMinimumSize(QtCore.QSize(300, 0))
        self.LoggedIn.setMaximumSize(QtCore.QSize(300, 16777215))
        self.LoggedIn.setStyleSheet("background-color: rgb(51, 58, 74);")
        self.LoggedIn.setObjectName("LoggedIn")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.LoggedIn)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 2, 300, 867))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.LoggedInLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.LoggedInLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.LoggedInLayout.setContentsMargins(0, 0, 0, 0)
        self.LoggedInLayout.setSpacing(0)
        self.LoggedInLayout.setObjectName("LoggedInLayout")
        self.menuBar = QtWidgets.QWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuBar.sizePolicy().hasHeightForWidth())
        self.menuBar.setSizePolicy(sizePolicy)
        self.menuBar.setMinimumSize(QtCore.QSize(225, 55))
        self.menuBar.setMaximumSize(QtCore.QSize(300, 55))
        self.menuBar.setStyleSheet("background-color: rgb(75, 85, 109);")
        self.menuBar.setObjectName("menuBar")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.menuBar)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(-1, -7, 300, 69))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Menu = QtWidgets.QToolButton(self.horizontalLayoutWidget_2)
        self.Menu.setStyleSheet(":hover {\n"
"    background-color: rgb(91, 103, 131);\n"
"}\n"
"\n"
"QToolButton {\n"
"    border:none;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/assets/menuBars.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Menu.setIcon(icon1)
        self.Menu.setIconSize(QtCore.QSize(60, 50))
        self.Menu.setObjectName("Menu")
        self.horizontalLayout.addWidget(self.Menu)
        self.Save = QtWidgets.QToolButton(self.horizontalLayoutWidget_2)
        self.Save.setStyleSheet(":hover {\n"
"    background-color: rgb(91, 103, 131);\n"
"}\n"
"\n"
"QToolButton {\n"
"    border:none;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Git/assets/download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Save.setIcon(icon2)
        self.Save.setIconSize(QtCore.QSize(60, 50))
        self.Save.setObjectName("Save")
        self.horizontalLayout.addWidget(self.Save)
        self.Logout = QtWidgets.QToolButton(self.horizontalLayoutWidget_2)
        self.Logout.setStyleSheet(":hover {\n"
"    background-color: rgb(91, 103, 131);\n"
"}\n"
"\n"
"QToolButton {\n"
"    border:none;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Git/assets/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Logout.setIcon(icon3)
        self.Logout.setIconSize(QtCore.QSize(60, 50))
        self.Logout.setObjectName("Logout")
        self.horizontalLayout.addWidget(self.Logout)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.LoggedInLayout.addWidget(self.menuBar)
        self.info = QtWidgets.QWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info.sizePolicy().hasHeightForWidth())
        self.info.setSizePolicy(sizePolicy)
        self.info.setMinimumSize(QtCore.QSize(225, 0))
        self.info.setMaximumSize(QtCore.QSize(300, 240))
        self.info.setObjectName("info")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.info)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(9, 3, 279, 233))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.firstname = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(20)
        self.firstname.setFont(font)
        self.firstname.setStyleSheet("background-color: rgb(111, 127, 161);")
        self.firstname.setFrame(False)
        self.firstname.setObjectName("firstname")
        self.verticalLayout_2.addWidget(self.firstname)
        self.lastname = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(20)
        self.lastname.setFont(font)
        self.lastname.setStyleSheet("background-color: rgb(111, 127, 161);")
        self.lastname.setFrame(False)
        self.lastname.setObjectName("lastname")
        self.verticalLayout_2.addWidget(self.lastname)
        self.lastused = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(20)
        self.lastused.setFont(font)
        self.lastused.setStyleSheet("background-color: rgb(111, 127, 161);")
        self.lastused.setFrame(False)
        self.lastused.setObjectName("lastused")
        self.verticalLayout_2.addWidget(self.lastused)
        self.accesslevel = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(20)
        self.accesslevel.setFont(font)
        self.accesslevel.setStyleSheet("background-color: rgb(111, 127, 161);")
        self.accesslevel.setFrame(False)
        self.accesslevel.setReadOnly(True)
        self.accesslevel.setObjectName("accesslevel")
        self.verticalLayout_2.addWidget(self.accesslevel)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(4, 1)
        self.LoggedInLayout.addWidget(self.info)
        self.scrollLabel = QtWidgets.QWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollLabel.sizePolicy().hasHeightForWidth())
        self.scrollLabel.setSizePolicy(sizePolicy)
        self.scrollLabel.setMinimumSize(QtCore.QSize(0, 50))
        self.scrollLabel.setObjectName("scrollLabel")
        self.label = QtWidgets.QLabel(self.scrollLabel)
        self.label.setGeometry(QtCore.QRect(8, 2, 273, 43))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label.setObjectName("label")
        self.LoggedInLayout.addWidget(self.scrollLabel)
        self.trackings = QtWidgets.QWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trackings.sizePolicy().hasHeightForWidth())
        self.trackings.setSizePolicy(sizePolicy)
        self.trackings.setObjectName("trackings")
        self.scrollArea = QtWidgets.QScrollArea(self.trackings)
        self.scrollArea.setGeometry(QtCore.QRect(9, -1, 294, 524))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 292, 522))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.LoggedInLayout.addWidget(self.trackings)
        self.LoggedInLayout.setStretch(0, 2)
        self.LoggedInLayout.setStretch(1, 5)
        self.LoggedInLayout.setStretch(2, 1)
        self.LoggedInLayout.setStretch(3, 10)
        self.stackedWidget.addWidget(self.LoggedIn)
        self.horizontalLayout_3.addWidget(self.stackedWidget)
        self.cameraArea = QtWidgets.QFrame(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameraArea.sizePolicy().hasHeightForWidth())
        self.cameraArea.setSizePolicy(sizePolicy)
        self.cameraArea.setStyleSheet("background-color: rgb(45, 51, 65);\n"
"background-image:    url(:/assets/camera.png);\n"
"background-repeat: no-repeat;\n"
"background-position: center;")
        self.cameraArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cameraArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cameraArea.setObjectName("cameraArea")
        self.horizontalLayout_3.addWidget(self.cameraArea)
        self.horizontalLayout_3.setStretch(1, 4)
        VisualSP.setCentralWidget(self.Main)

        self.retranslateUi(VisualSP)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(VisualSP)

    def retranslateUi(self, VisualSP):
        _translate = QtCore.QCoreApplication.translate
        VisualSP.setWindowTitle(_translate("VisualSP", "MainWindow"))
        self.loginLabel.setText(_translate("VisualSP", "Login"))
        self.userName.setPlaceholderText(_translate("VisualSP", "Username"))
        self.loginButton.setText(_translate("VisualSP", "..."))
        self.loginButton.setShortcut(_translate("VisualSP", "Return"))
        self.toolButton.setText(_translate("VisualSP", "New User"))
        self.Menu.setText(_translate("VisualSP", "..."))
        self.Save.setText(_translate("VisualSP", "..."))
        self.Logout.setText(_translate("VisualSP", "..."))
        self.label_2.setText(_translate("VisualSP", "USERNAME"))
        self.firstname.setPlaceholderText(_translate("VisualSP", "First Name"))
        self.lastname.setPlaceholderText(_translate("VisualSP", "Last Name"))
        self.lastused.setPlaceholderText(_translate("VisualSP", "Last Used"))
        self.accesslevel.setPlaceholderText(_translate("VisualSP", "Access Level"))
        self.label.setText(_translate("VisualSP", "Previous Trackings"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VisualSP = QtWidgets.QMainWindow()
    ui = Ui_VisualSP()
    ui.setupUi(VisualSP)
    VisualSP.show()
    sys.exit(app.exec_())

